from pathlib import Path

root = Path(__file__).resolve().parents[1]
exam_dir = root / "exams"
files = sorted(p.name for p in exam_dir.glob("exam_*.js") if p.name != "exam_template.js")

content = "// Auto-generated by tools/rebuild_exam_index.py\nwindow.EXAM_FILES = [\n"
content += "\n".join(f'  "{name}",' for name in files)
content += "\n];\n"

(exam_dir / "index.js").write_text(content, encoding="utf-8")
print(f"Wrote exams/index.js with {len(files)} exam file(s).")
